(function(){var g=this;var aa=function(a,b,d){a.addEventListener?a.addEventListener(b,d,!1):a.attachEvent&&a.attachEvent("on"+b,d)};var k=function(a){return{visible:1,hidden:2,prerender:3,preview:4}[a.webkitVisibilityState||a.mozVisibilityState||a.visibilityState||""]||0},ba=function(a){var b;a.mozVisibilityState?b="mozvisibilitychange":a.webkitVisibilityState?b="webkitvisibilitychange":a.visibilityState&&(b="visibilitychange");return b},n=function(a,b){if(3==k(b))return!1;a();return!0},ca=function(a,b){if(!n(a,b)){var d=!1,c=ba(b),e=function(){if(!d&&n(a,b)){d=!0;var f=e;b.removeEventListener?b.removeEventListener(c,f,!1):b.detachEvent&&
b.detachEvent("on"+c,f)}};c&&aa(b,c,e)}};var t=function(a){a=parseFloat(a);return isNaN(a)||1<a||0>a?0:a};var da=t("0.04"),ea=t("0.01"),ha=t("0.0"),ia=t("0.01");var ja=/^true$/.test("false")?!0:!1;var u=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},v=function(a,b){return a<b?-1:a>b?1:0};var w;a:{var x=g.navigator;if(x){var y=x.userAgent;if(y){w=y;break a}}w=""};var ka=-1!=w.indexOf("Opera"),z=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),la=-1!=w.indexOf("Edge"),A=-1!=w.indexOf("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"))&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"))&&-1==w.indexOf("Edge"),ma=-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"),B=function(){var a=g.document;return a?a.documentMode:void 0},C;
a:{var D="",E=function(){var a=w;if(A)return/rv\:([^\);]+)(\)|;)/.exec(a);if(la)return/Edge\/([\d\.]+)/.exec(a);if(z)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(ma)return/WebKit\/(\S+)/.exec(a);if(ka)return/(?:Version)[ \/]?(\S+)/.exec(a)}();E&&(D=E?E[1]:"");if(z){var F=B();if(null!=F&&F>parseFloat(D)){C=String(F);break a}}C=D}
var G=C,H={},I=function(a){if(!H[a]){for(var b=0,d=u(String(G)).split("."),c=u(String(a)).split("."),e=Math.max(d.length,c.length),f=0;0==b&&f<e;f++){var h=d[f]||"",l=c[f]||"",q=RegExp("(\\d*)(\\D*)","g"),p=RegExp("(\\d*)(\\D*)","g");do{var m=q.exec(h)||["","",""],r=p.exec(l)||["","",""];if(0==m[0].length&&0==r[0].length)break;b=v(0==m[1].length?0:parseInt(m[1],10),0==r[1].length?0:parseInt(r[1],10))||v(0==m[2].length,0==r[2].length)||v(m[2],r[2])}while(0==b)}H[a]=0<=b}},J=g.document,na=J&&z?B()||
("CSS1Compat"==J.compatMode?parseInt(G,10):5):void 0;var K=function(a){K[" "](a);return a};K[" "]=function(){};var L;if(!(L=!A&&!z)){var M;if(M=z)M=9<=Number(na);L=M}L||A&&I("1.9.1");z&&I("9");var N=function(a,b){for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.call(void 0,a[d],d,a)};var O=function(a,b,d){for(;0<=(b=a.indexOf("fmt",b))&&b<d;){var c=a.charCodeAt(b-1);if(38==c||63==c)if(c=a.charCodeAt(b+3),!c||61==c||38==c||35==c)return b;b+=4}return-1},P=/#|$/,oa=/[?&]($|#)/;var pa=function(){this.b={};this.a={};this.c=!1;for(var a=[1,2,3,4],b=0,d=a.length;b<d;++b)this.a[a[b]]=""},R=function(a,b,d){var c=Q;if(!c.c&&(d?c.a.hasOwnProperty(d)&&""==c.a[d]:1)){var e;a:{try{var f=window.top.location.hash;if(f){var h=f.match(/\bdeid=([\d,]+)/);e=h&&h[1]||"";break a}}catch(q){}e=""}if(e=(e=e.match(new RegExp("\\b("+a.join("|")+")\\b")))&&e[0]||null)a=e;else a:{if(!(1E-4>Math.random())&&(e=Math.random(),e<b)){b=window;try{var l=new Uint32Array(1);b.crypto.getRandomValues(l);e=
l[0]/65536/65536}catch(q){e=Math.random()}a=a[Math.floor(e*a.length)];break a}a=null}a&&""!=a&&(d?c.a.hasOwnProperty(d)&&(c.a[d]=a):c.b[a]=!0)}},S=function(a){var b=Q;return b.a.hasOwnProperty(a)?b.a[a]:""},qa=function(){var a=Q,b=[];N(a.b,function(a,c){b.push(c)});N(a.a,function(a){""!=a&&b.push(a)});return b};var Q,T="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_remarketing_only google_remarketing_for_search google_conversion_items google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_conversion_page_url google_conversion_referrer_url".split(" "),
U=["google_conversion_first_time","google_conversion_snippets"];function V(a){return null!=a?"345553315"==(Q?S(2):"")?encodeURIComponent(a.toString()):escape(a.toString()):""}function ra(a){return null!=a?a.toString().substring(0,512):""}function W(a,b){var d=V(b);if(""!=d){var c=V(a);if(""!=c)return"&".concat(c,"=",d)}return""}function X(a){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")}
function sa(a){var b;if((a=a.google_custom_params)&&"object"==typeof a&&"function"!=typeof a.join){var d=[];for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b];if(c&&"function"==typeof c.join){for(var e=[],f=0;f<c.length;++f){var h=X(c[f]);null!=h&&e.push(h)}c=0==e.length?null:e.join(",")}else c=X(c);(e=X(b))&&null!=c&&d.push(e+"="+c)}b=d.join(";")}else b="";return""==b?"":"&".concat("data=",encodeURIComponent(b))}
function ta(a){if(null!=a){a=a.toString();if(2==a.length)return W("hl",a);if(5==a.length)return W("hl",a.substring(0,2))+W("gl",a.substring(3,5))}return""}function Y(a){return"number"!=typeof a&&"string"!=typeof a?"":V(a.toString())}
function ua(a){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],d=0,c=a.length;d<c;d++){var e=a[d],f=[];e&&(f.push(Y(e.value)),f.push(Y(e.quantity)),f.push(Y(e.item_id)),f.push(Y(e.adwords_grouping)),f.push(Y(e.sku)),b.push("("+f.join("*")+")"))}return 0<b.length?"&item="+b.join(""):""}
function va(a,b,d){var c=[];if(a){var e=a.screen;e&&(c.push(W("u_h",e.height)),c.push(W("u_w",e.width)),c.push(W("u_ah",e.availHeight)),c.push(W("u_aw",e.availWidth)),c.push(W("u_cd",e.colorDepth)));a.history&&c.push(W("u_his",a.history.length))}d&&"function"==typeof d.getTimezoneOffset&&c.push(W("u_tz",-d.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&&c.push(W("u_java",b.javaEnabled())),b.plugins&&c.push(W("u_nplug",b.plugins.length)),b.mimeTypes&&c.push(W("u_nmime",b.mimeTypes.length)));
return c.join("")}function wa(a){a=a?a.title:"";if(void 0==a||""==a)return"";var b=function(a){try{return decodeURIComponent(a),!0}catch(b){return!1}};a=encodeURIComponent(a);for(var d=256;!b(a.substr(0,d));)d--;return"&tiba="+a.substr(0,d)}
function xa(a,b,d,c){var e="";if(b){var f;if(a.top==a)f=0;else{var h=a.location.ancestorOrigins;if(h)f=h[h.length-1]==a.location.origin?1:2;else{h=a.top;try{var l;if(l=!!h&&null!=h.location.href)c:{try{K(h.foo);l=!0;break c}catch(q){}l=!1}f=l}catch(q){f=!1}f=f?1:2}}a=d?d:1==f?a.top.location.href:a.location.href;e+=W("frm",f);e+=W("url",ra(a));e+=W("ref",ra(c||b.referrer))}return e}
function Z(a,b){return!(ja||b&&ya.test(navigator.userAgent))||a&&a.location&&a.location.protocol&&"https:"==a.location.protocol.toString().toLowerCase()?"https:":"http:"}function za(a,b,d){d=d.google_remarketing_only?"googleads.g.doubleclick.net":d.google_conversion_domain||"www.googleadservices.com";return Z(a,/www[.]googleadservices[.]com/i.test(d))+"//"+d+"/pagead/"+b}
function Aa(a,b,d,c){var e="/?";"landing"==c.google_conversion_type&&(e="/extclk?");e=[c.google_remarketing_only?"viewthroughconversion/":"conversion/",V(c.google_conversion_id),e,"random=",V(c.google_conversion_time)].join("");e=za(a,e,c);a=[W("cv",c.google_conversion_js_version),W("fst",c.google_conversion_first_time),W("num",c.google_conversion_snippets),W("fmt",c.google_conversion_format),W("value",c.google_conversion_value),W("currency_code",c.google_conversion_currency),W("label",c.google_conversion_label),
W("oid",c.google_conversion_order_id),W("bg",c.google_conversion_color),ta(c.google_conversion_language),W("guid","ON"),W("disvt",c.google_disable_viewthrough),W("eid",qa().join()),ua(c),va(a,b,c.google_conversion_date),sa(c),xa(a,d,c.google_conversion_page_url,c.google_conversion_referrer_url),c.google_remarketing_for_search&&!c.google_conversion_domain?"&srr=n":"",wa(d)].join("");return e+a}
var Ba=function(a,b,d,c,e,f){return'<iframe name="'+a+'" title="'+b+'" width="'+c+'" height="'+e+'" src="'+d+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true"'+(f?' style="display:none"':"")+' scrolling="no"></iframe>'};
function Ca(a){return{ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[a]?a+".html":"en_US.html"}
var ya=/Android ([01]\.|2\.[01])/i,Da=function(a,b){if(!b.google_remarketing_only||"376635471"!=(Q?S(3):""))return"";var d=Z(a,!1)+"//bid.g.doubleclick.net/xbbe/pixel?d=KAE";return Ba("google_cookie_match_frame","Google cookie match frame",d,1,1,!0)};
function Ea(a,b,d,c){3!=c.google_conversion_format||c.google_remarketing_only||c.google_conversion_domain||Q&&R(["317150500","317150501","317150504","317150505"],da,1);var e="";c.google_remarketing_only&&(Q&&R(["376635470","376635471"],ha,3),e=Da(a,c));Q&&R(["345553314","345553315"],ea,2);var f=Q?S(1):"";""!==f||3!=c.google_conversion_format||c.google_remarketing_only||c.google_conversion_domain||Q&&R(["27391101","27391102"],ia,4);b=Aa(a,b,d,c);var h=function(a,b,c,d){return'<img height="'+c+'" width="'+
b+'" border="0" alt="" src="'+a+'"'+(d?' style="display:none"':"")+" />"};return 0==c.google_conversion_format&&null==c.google_conversion_domain?'<a href="'+(Z(a,!1)+"//services.google.com/sitestats/"+Ca(c.google_conversion_language)+"?cid="+V(c.google_conversion_id))+'" target="_blank">'+h(b,135,27,!1)+"</a>"+e:1<c.google_conversion_snippets||3==c.google_conversion_format?"317150501"==f||"317150504"==f||"317150505"==f?h(b,1,1,!0)+('<script src="'+b.replace(/(&|\?)fmt=3(&|$)/,"$1fmt=4&adtest=on$2")+
'">\x3c/script>')+e:""===f&&Fa(d,b)?e:h(b,1,1,!0)+e:Ba("google_conversion_frame","Google conversion frame",b,2==c.google_conversion_format?200:300,2==c.google_conversion_format?26:13,!1)+e}function Ga(){return new Image}
function Fa(a,b){if("27391102"==(Q?S(4):""))try{var d;var c;var e=b.search(P),f=O(b,0,e);if(0>f)c=null;else{var h=b.indexOf("&",f);if(0>h||h>e)h=e;f+=4;c=decodeURIComponent(b.substr(f,h-f).replace(/\+/g," "))}if(3!=c)d=!1;else{var l=b.search(P);c=0;for(var q,e=[];0<=(q=O(b,c,l));)e.push(b.substring(c,q)),c=Math.min(b.indexOf("&",q)+1||l,l);e.push(b.substr(c));var p=[e.join("").replace(oa,"$1"),"&","fmt"];p.push("=",encodeURIComponent("4"));if(p[1]){var m=p[0],r=m.indexOf("#");0<=r&&(p.push(m.substr(r)),
p[0]=m=m.substr(0,r));var fa=m.indexOf("?");0>fa?p[1]="?":fa==m.length-1&&(p[1]=void 0)}var ga=a.createElement("script");ga.src=p.join("");a.getElementsByTagName("script")[0].parentElement.appendChild(ga);d=!0}return d}catch(Na){}return!1}function Ha(a,b){var d=a.opt_image_generator&&a.opt_image_generator.call;b+=W("async","1");var c=Ga;d&&(c=a.opt_image_generator);d=c();d.src=b;d.onload=function(){}}
function Ia(a,b,d){var c=Math.floor(1E9*Math.random()),c=[V(d.google_conversion_id),"/?random=",c].join(""),c=Z(a,!1)+"//www.google.com/ads/user-lists/"+c;a=[W("label",d.google_conversion_label),W("fmt","3"),xa(a,b,d.google_conversion_page_url,d.google_conversion_referrer_url)].join("");Ha(d,c+a)}
function Ja(a){if("landing"==a.google_conversion_type||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();a.google_conversion_snippets="number"==typeof a.google_conversion_snippets&&0<a.google_conversion_snippets?a.google_conversion_snippets+1:1;"number"!=typeof a.google_conversion_first_time&&(a.google_conversion_first_time=a.google_conversion_time);a.google_conversion_js_version=
"8";0!=a.google_conversion_format&&1!=a.google_conversion_format&&2!=a.google_conversion_format&&3!=a.google_conversion_format&&(a.google_conversion_format=1);Q=new pa;return!0}function Ka(a){for(var b=0;b<T.length;b++)a[T[b]]=null}function La(a){for(var b={},d=0;d<T.length;d++)b[T[d]]=a[T[d]];for(d=0;d<U.length;d++)b[U[d]]=a[U[d]];return b}
function Ma(a){var b=document.getElementsByTagName("head")[0];b||(b=document.createElement("head"),document.getElementsByTagName("html")[0].insertBefore(b,document.getElementsByTagName("body")[0]));var d=document.createElement("script");d.src=za(window,"conversion_debug_overlay.js",a);b.appendChild(d)};(function(a,b,d){if(a)if(null!=/[\?&;]google_debug/.exec(document.URL))Ma(a);else{try{if(Ja(a))if(3==k(d)){var c=La(a),e="google_conversion_"+Math.floor(1E9*Math.random());d.write('<span id="'+e+'"></span>');ca(function(){try{var f=d.getElementById(e);f&&(f.innerHTML=Ea(a,b,d,c),c.google_remarketing_for_search&&!c.google_conversion_domain&&Ia(a,d,c))}catch(h){}},d)}else d.write(Ea(a,b,d,a)),a.google_remarketing_for_search&&!a.google_conversion_domain&&Ia(a,d,a)}catch(f){}Ka(a)}})(window,navigator,
document);}).call(this);
